eureka:
  client:
    instance:
      preferIpAddress:true
    service-url:
      defaultZone: http://localhost:8761/eureka
debug: true
spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: user-client
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8081

